### ISSUE TITLE
ET Feedback on this-week-in-solid/2020-01-09-this-week-in-solid.md

### ISSUE THREAD

**Issue by emmettownsend** [solid/solidproject.org#113]
Rubens comments included below.

https://github.com/solid/solidproject.org/pull/102 is not merged yet (Tim needs to approve it ASAP), the newsletter will be rendered with the incorrect "Solid is a standard" on top instead of the technically accurate intro here https://solid.github.io/this-week-in-solid/2020-01-09

In the sentence below, typos is the correct spelling, not typo's
Additionally, most content has undergone editing to ensure the information is relevant and free of typo's.

In the sentence below we should let Mark H state whether it works with Firefox or not on his page rather than us stating it. 
Mark Hughes is working on showing how to use various RDF libs with Sveltejs and has rdflib.js and graphy working (though graphy only works in Chrome not Firefox atm).

[Molid]] I assume the double ending bracket is not intentional?

In the sections "Developer Tools" and "Apps, Pods, and Identity Providers" we should provide some context about the items we are referencing. Why they are useful, what they are , how they fit into the ecosystem. Otherwise we are just providing a set of links without useful context.

**Comment by Vinnl** [comment]
> #102 is not merged yet (Tim needs to approve it ASAP), the newsletter will be rendered with the incorrect "Solid is a standard" on top instead of the technically accurate intro here https://solid.github.io/this-week-in-solid/2020-01-09

Since this edition of TWiS is developed in the `staging` branch as well, it will be included in the review of #102.

I've assigned Mitzi to deal with the other points.
