### ISSUE TITLE
Suggestions for "This week in Solid"

### ISSUE THREAD

**Issue by karlicoss** [solid/solidproject.org#120]
Solid project looks very interesting to me, so I wanted to:

- read about its future development. However I wasn't able to find an RSS feed anywhere. Is there one? Wouldn't it make sense to add it? 

- read about its past development and activity. So I went through past pages on [This week in Solid]( https://solidproject.org/this-week-in-solid), and they all seemed very repetitive, e.g.

  - large [header](https://github.com/solid/solidproject.org/blob/staging/_includes/twis-intro.md), included and repeated in every letter
  - same job postings repeated 
  - same event announcements repeated

   I understand that probably makes sense for a newsletter, but when reading them back on the website, it's hard to pick out what potential users might be intersted at (project updates and new apps). Wonder if for the website it would make sense to generate versions of newsletters stripped out off repetitive stuff.

Thanks!

**Comment by Mitzi-Laszlo** [comment]
Hi @karlicoss, 

Thanks for taking the time to share your feedback on This Week in Solid. 

One way of going about it is just to link to the upcoming [press](https://solidproject.org/press) page and let people read it directly but there are others who have wanted all the information directly in the newsletter so they don't have to click away. The other thing would be to only mention the events the moment they are confirmed and then take them down. In that case, people might miss the information if they don't carefully read all the newsletters. Both work, guess it's a matter of preference, open to all routes. 

Probably it only makes sense to read the latest edition if you are really looking for the latest updates?

**Comment by Mitzi-Laszlo** [comment]
The comments have been incorporated. If there are any other changes please do say, there's a ticket for creating an RSS feed on the kanban board for someone to pick up when available. https://github.com/solid/solidproject.org/issues/259
