### ISSUE TITLE
List Experimental Pods

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/solidproject.org#124]
Perhaps this list could be in the developer material so they know where to test against?

**Comment by NSeydoux** [comment]
When you say experimental Pods, are you talking about certain Pods specifically, like Cleopatra's and Ceasar's ? In this case they are directly referenced in the tutorials, and I think encouraging developers to get their own experimental Pod (where they can actually control permissions) might be more scalable, as in the current situation it is necessary to clean up the experimental Pods we manage manually once in a while

**Comment by megoth** [comment]
I think what was intended is listing experimental _Pod providers_, e.g. Solid servers that are set up for testing but not intended to have 100% uptime and such.

**Comment by NSeydoux** [comment]
Oh my bad, I misunderstood, then yes absolutely.

**Comment by mikeadams1** [comment]
I think solid.commuinty should be included on solidproject.org along with solid.authig.cn and inrupt.net as pod providers. From what I understand, solid.community is the free pod provider and inrupt.net a commercial pod provider.
