### ISSUE TITLE
Two (four) double entries in the FAQ section

### ISSUE THREAD

**Issue by ewingson** [solid/solidproject.org#132]
@Vinnl @NSeydoux 

in https://solidproject.org/faqs
- Could Solid become another tech giant monopoly? and
- Could a Solid app of Pod become another tech giant monopoly?

are mentioned double.

I wasn' t sure if to remove the upper(top) or the lower(bottom) copies regarding the desired order, so I opened an issue instead of a PR.
and typo `or` for `of`

**Comment by Vinnl** [comment]
@Mitzi-Laszlo You added them, do you know which one to leave in?

**Comment by Mitzi-Laszlo** [comment]
Thank you @ewingson for taking the time to find and give this feedback. The questions are indeed similar although ever so slightly different because Solid is not the same as a Solid app (or Pod) so it's still sensible to have two separate FAQs.
