### ISSUE TITLE
Add Solidarity Link

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/solidproject.org#150]
https://scenaristeur.github.io/solidarity/archive/

**Comment by scenaristeur** [comment]
Sorry, I didn't see your gutter message.
Thxs @Mitzi-Laszlo  for making Solidarity more visible. 
https://scenaristeur.github.io/solidarity/archive/ is a temporary mobile version. 
The computer version is at https://scenaristeur.github.io/solidarity/
@Julian-Cole and me are working on this project. @Julian as a designer and I for the Shighl
API to simplify interaction with a Pod. https://github.com/scenaristeur/shighl with the aim to build reusable components quite similar to react - components https://github.com/scenaristeur/shighl-elements
There is a lot to do more and any help is welcome.
