### ISSUE TITLE
Should we list applications on solidproject.org

### ISSUE THREAD

**Issue by justinwb** [solid/solidproject.org#161]
Creating a standalone issue based on [this comment](https://github.com/solid/solidproject.org/pull/160#issuecomment-595352371). Quoted below:

> As a general point, I question whether we should be listing specific applications on solidproject.org. How do we ensure that these applications don't harm (intentionally or unintentionally) someone's personal dataset, and reflect poorly on the project as a whole? Could listing apps directly on the site mislead users into thinking that they are officially endorsed by the solid project, and have been quality tested for safety? At a minimum, what is (or isn't) happening, should be well-articulated, and there should be some warnings and/or disclaimers. I question the benefit vs. the risk.

> Though a similar argument could be made for tooling, I think that is OK to include. IMO, tooling undergoes more general scrutiny (in use and as source code). Developers tend to do a subsequent evaluation pass by a more informed audience before they incorporate tools into their project. Even still, i think we should only be listing tooling that we have greater confidence in.

**Comment by InruptKelly** [comment]
Tough question — I agree there’s a risk of overpromising (especially with the current format seeming to endorse the “Showcase” apps), but it seems really valuable to have an easily accessible list of apps that people can try out and learn from.

We could at least add much clearer disclaimer text to point out that anyone can add their own app to this list and thus there are no security or quality guarantees.

Maybe we also need a lightweight mechanism for removing apps from the list if they’re found to be damaging. (I’ve seen complaints against Pixolid [here](https://github.com/carloss8/pixolid/issues/1) and elsewhere, for example.) A small process could look like this:

- Raise an issue [here](https://github.com/solid/solidproject.org/edit/staging/pages/use-solid/apps.md) indicating what is wrong with the app and why you think it should be removed. Tag the person who created the app.
- Wait 24 hours for the app’s creator or maintainer to respond.
- If the creator or maintainer of the app does not respond within 24 hours to indicate that they will fix the problem, a Solid Administrator will remove the app from the listing.

**Comment by NSeydoux** [comment]
I think it is important to show the liveliness of the community by promoting apps on the website, so that new-coming developers and power users can have some concrete stuff to put there hands on.

However, I agree that it should be made very clear that anyone can submit an application to appear on this website, and therefore that there is no guarantee of any kind. I think we can also say that the apps that appear in the "Showcase" section have gone through more scrutiny (e.g. some of them are by inrupt employees, of long-time contributors to the community). 

I think the process @InruptKelly proposes is a good way forward.

**Comment by InruptKelly** [comment]
OK great, I can volunteer to raise an issue about Pixolid.

How else can I help us move forward? Should I make a PR on the app listing page with a suggestion for disclaimer language?

**Comment by Vinnl** [comment]
That would be great @InruptKelly. Only suggestion would be to link the "Raise an issue" link to https://github.com/solid/solidproject.org/issues/new, where people (GitHub users) can actually be tagged.

**Comment by InruptKelly** [comment]
Got it, thanks!

Added an issue [here](https://github.com/solid/solidproject.org/issues/168) and submitted a PR [here](https://github.com/solid/solidproject.org/pull/167)

(My first-ever PR, so let me know if I messed something up.

**Comment by Vinnl** [comment]
Flawless PR Kelly :)

I'll close this issue, but if anyone thinks it's insufficiently dealt with, let me know.

**Comment by csarven** [comment]
RFC https://github.com/solid/solidproject.org/pull/169#discussion_r394942945 on reviewing requests.

**Comment by Vinnl** [comment]
I'm re-opening this based on a comment by @csarven:

> I think 24 hours is a short notice. Perhaps a week? If no response, the Solid Administrator should review the removal request and the app. It prevents arbitrary removal requests and removing without an actual review (if creator/maintainer doesn't show up on time).

How about updating the text as follows:

```diff
- If you believe one of the apps below is insecure or non-functional and should be removed from the list, please raise an issue [here] (https://github.com/solid/solidproject.org/issues) and tag the app's creator or maintainer. If the creator or maintainer of the app does not respond within 24 hours to indicate that they will fix the problem, a Solid Administrator will remove the app from the listing.
+ If you believe one of the apps below is insecure or non-functional and should be removed from the list, please raise an issue [here](https://github.com/solid/solidproject.org/issues) and tag the app's author or maintainer. If the author or maintainer of the app does not respond within a week to indicate that they will fix the problem, a Solid Administrator or Creator will review the concerns and, if justified, remove the app from the listing.
```

Which would result in:

> If you believe one of the apps below is insecure or non-functional and should be removed from the list, please raise an issue [here](https://github.com/solid/solidproject.org/issues) and tag the app's author or maintainer. If the author or maintainer of the app does not respond within a week to indicate that they will fix the problem, a Solid Administrator or Creator will review the concerns and, if justified, remove the app from the listing.

**Comment by justinwb** [comment]
So if someone reports an app as insecure - and it is - all the author has to do is not respond so it stays up for a week?

**Comment by Vinnl** [comment]
An _additional_ week, in addition to how long it's already been listed.

I'm also wondering if we should replace "will" by "can", given that we probably won't be able to respond in exactly a week always.

**Comment by RubenVerborgh** [comment]
I find it _very_ scary to list that text in TWiS. It sounds like we don't have security under control.

**Comment by justinwb** [comment]
I keep circling back to the core issue that I raised to start this thread. One bad application, listed on the main project website (http://solidproject.org), could sully the reputation and trust of the project and the technology for a long time. In my opinion, this risk is not worth it. There should be more separation between the core site/technology and the ecosystem around it, so that issues with the latter don't pollute the former. 

One possible compromise (for the time being):

1. Remove application listing from solidproject.org 
1. Create a moderated section on https://forum.solidproject.org
1. Developer can submit a new thread to share their application (this is happening to an extent already),  that requires moderator approval before activating. Moderator does some bit of checking on their own first.
1. Other community members evaluate a shared application and provide some review that others can read
1. Critical reviews by the community result in the application getting flagged and action taken by moderator(s)
1. Positive reviews by the community will similarly be reflected by the volume and tone/tenor of community feedback.

My personal thoughts on this compromise approach:
- It still has an association with the project since it's on the solidproject.org forum, which I don't love, but since it is a forum the proposed apps are more strongly coupled to the OP, and less to the project.
- Has the benefit of documented community review built into the forum, in the same place people would find the app. Otherwise, if issues with an app live on github, how would someone evaluating whether to use it on www.solidproject.org have any idea that those issues exist (and what they are)?
- Eventually this should be replaced by real app registries and app stores. 
- I'm not overjoyed with this approach, but it seems like an improvement over what we're doing now.

**Comment by csarven** [comment]
Ruben,

>I find it very scary to list that text in TWiS. It sounds like we don't have security under control.

An app may pass initial review and get listed, and at a later date may become an issue (intentionally or not). Hence, a review of the request to remove at any time is necessary.

**Comment by Mitzi-Laszlo** [comment]
The app listing criteria is published, if anyone would like to edit further please submit a pull request with a specific edit to the copy.

**Comment by jeff-zucker** [comment]
It seems like we are leaning toward @justinwb's proposal to have a featured apps section on the site and  move all other apps  to the forum.  As mentioned in the team meeting, we should think about having a landing page for the forum that clearly lists out the forum sections so users know where the apps are.  Possibly we should have categories like "app listings", "app  reviews", "app questions" so that we keep the listing of apps clean of "how do I use this" questions but have a clear place where those questions should go.  This will take both an initial setup stage and ongoing maintenance - shouldn't be a huge amount of work, but a minimum in my view would be moving/removing everything but app announcements from the apps list on the forum.
