### ISSUE TITLE
Use canonical HTTP link for Creative Commons examples

### ISSUE THREAD

**Issue by Vinnl** [solid/solidproject.org#170]
As noted [here](https://github.com/solid/solidproject.org/pull/169#pullrequestreview-377664903), we point to https://creativecommons.org/licenses/by/4.0/ in example files whereas [the canonical URL is non-HTTPS](https://github.com/solid/solidproject.org/pull/169#issuecomment-601236827). However, the HTTP link is failing, causing our builds to fail.

Unfortunately, it does not appear to be possible to tell [html-proofer](https://github.com/gjtorikian/html-proofer) to ignore a single URL to check.

So we have three options, I think:

1. Keep the incorrect URL.
2. Disable the external links check.
3. Update the example to not use Creative Commons.

Option 1. doesn't seem desirable. @NSeydoux, do you know if 3. is a reasonable option?

/cc @RubenVerborgh

**Comment by NSeydoux** [comment]
Well there were additional comments by @csarven in #169 which suggests that we could stick to using the `https` IRI. I'm fine removing it altogether from the examples, as 2. does not seem to be a desirable option either.

**Comment by Vinnl** [comment]
Ah, I see. I'll close this then, but if someone has additional concerns, let me know, then I'll re-open this.
