### ISSUE TITLE
Links in footer is not visible on smaller screens

### ISSUE THREAD

**Issue by megoth** [solid/solidproject.org#25]
<img width="624" alt="Screen Shot 2019-12-13 at 15 17 28" src="https://user-images.githubusercontent.com/775139/70806471-b6221c00-1dbb-11ea-858f-1428b8828019.png">

**Comment by FutureLearnSole** [comment]
#103 major

**Comment by NSeydoux** [comment]
I cannot reproduce the issue. @megoth, is it still a problem ? I know styling has been refactored since the issue was open, so it may have resolved the problem. If so, I'll close the ticket.

**Comment by megoth** [comment]
No, this does not seem to be an issue anymore, not able to reproduce it at least 😸
