### ISSUE TITLE
Spell check broken

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solidproject.org#269]
https://github.com/solid/solidproject.org/commit/1c9c9fd042ef0c44e70fb0530653489ece3b1afb broke spell check.

The intent seemed to have been to make it a warning; however, `| true` actually creates a _pipe_ to the `true` command:
https://travis-ci.org/github/solid/solidproject.org/builds/706813780#L439

> log writing failed. Broken pipe @ io_write - <STDOUT>

Let's re-enable spell check; I'm not saying it should necessarily fail the build (although I think it should), but there used to be a high volume of spelling errors on the site, which we should at least be able to keep an eye on.

**Comment by Vinnl** [comment]
Whoops, thanks for reporting and identifying the issue.

Unfortunately the overhead of keeping the dictionary up-to-date as we go was a bit too high for the resources we have; instead, we intended to go over the reported errors every once in a while and fix them in one go, which is significantly more efficient.
