### ISSUE TITLE
Documentation for NSS on a root machine

### ISSUE THREAD

**Issue by ewingson** [solid/solidproject.org#301]
@Vinnl @NSeydoux @Mitzi-Laszlo 
as requested I propose to extend the existing documentation in https://solidproject.org/for-developers/pod-server and https://solidproject.org/for-developers/pod-server/apache.
I have put together some docs for maintaining a root machine and install NSS with Nginx as reverse proxy (which seems more up-to-date than apache). you can find it here https://gist.github.com/ewingson/c6e97a996aa51eac9f7fd1b7eaf14dc4
someone with experience how to create and format sites on solidproject.org would be needed for help.
what still needs to be done is replace the server name with `example.org`.
maybe we could reorganize the 'developer'-section to include both ways.

what do you think ?

**Comment by NSeydoux** [comment]
Thanks for putting together the doc, it's true that Nginx is widely used for reverse proxies. I can put together a new page that would be displayed in the right-hand column, under "Use apache as a reverse proxy" on https://solidproject.org/for-developers/pod-server, and then you could fill the page with your markdown content. Does that sound okay to you ?

**Comment by ewingson** [comment]
yeah, sounds good. maybe you create an empty page and do the linking and I look at https://github.com/solid/solidproject.org/blob/staging/_posts/for-developers/pod-server/2019-01-02-00_apache-config.md for some inspiration ??

**Comment by NSeydoux** [comment]
I just pushed a commit with the new page and a draft of the content that you shared in the first post of the issue. You can find it at https://github.com/solid/solidproject.org/tree/doc/nginx-reverse-proxy, so feel free to tweak it so that it reflects the content you intended :)

**Comment by ewingson** [comment]
cool but docker' s unknown territory for me ;-) have done so far all changes, so the page looks equivalent to the apache config. would you do the linking (menu) ?

**Comment by ewingson** [comment]
cool thanx, beneath the 'Apache' link in https://solidproject.org/for-developers/pod-server should go the nginx link and the menu on the right site needs tweaking.... (lotsa things to learn in solid, but I feel its documentation worth doing, THANX)

**Comment by ewingson** [comment]
has made its way into the site, so closed.
