### ISSUE TITLE
what WYSIWYG editor editors here?

### ISSUE THREAD

**Issue by FutureLearnSole** [solid/solidproject.org#318]
@editors

this use Bulma framework, browser React no read

That is all me know

**Data should empower you,**

**Comment by FutureLearnSole** [comment]
need to see a render somehow before commits here of my Bulma based drafsts

**Comment by Vinnl** [comment]
We don't have a WYSIWYG editor, unfortunately. If you have the repository locally and Docker Compose installed, you can run `docker-compose up` to see what it will look like. Other than that, if your PRs are merged they will appear on the solid.github.io draft site first, before being published to solidproject.org, so you can give them a quick look to see whether everything looks as intended.

I'll see if I can set something up that allows you to verify your changes _before_ merging them.

**Comment by FutureLearnSole** [comment]
# am satisfies with this solution, Biggest thanks

**Comment by Vinnl** [comment]
@FutureLearnSole I think I might have it set up now that it will create a deployment somewhere if you submit a PR. I'm just not sure yet whether that also works if you've created your PR from a fork. Could you update on of your PRs and see if that triggers a deployment?

**Comment by Vinnl** [comment]
Hmm, looks like deployments of repositories in a team are not part of Vercel's free plan, and that we were part of a trial: https://github.com/solid/solidproject.org/commit/4bf3980c4049c9b796af038869212428ebacc180#commitcomment-41910851

So unfortunately the preview links are disabled again :/ Hopefully the Docker solution is sufficient for now.
