### ISSUE TITLE
Subscribe to 'This Month in Solid' sends email for 'This Week in Solid'

### ISSUE THREAD

**Issue by smessie** [solid/solidproject.org#379]
**Search terms you've used**

week in solid / month in solid

**Describe the bug**
There is inconsistency between the site where it said I could subscribe to 'This Month in Solid' and the email I received after subscribing to the site with a confirmation for 'This Week in Solid'.
Email:
> Click the link below to confirm your subscription to This Week in Solid:
> Subscribe me to This Week in Solid

**To Reproduce**
1. Go to the bottom of https://solidproject.org
2. Fill in your email and click on 'Subscribe'
3. Open your received email.
4. See inconsistency.

**Expected behavior**
I suppose it is now called 'This Month in Solid', so I expect this to be named in the email the same way.

**Desktop (please complete the following information):**
 - OS: macOS 10.17.5
 - Browser: Safari
 - Version: 14.0

**Comment by MarrelleBailey** [comment]
Hi @smessie, thank you for pointing this out. We have made the changes; it is now This Month in Solid.

**Comment by Vinnl** [comment]
(I suppose it'll take another two weeks before you can actually see it, but I'll close this assuming that it's fixed. Feel free to reopen if it's not. Thanks for the notification!)
