### ISSUE TITLE
Broken link on front page

### ISSUE THREAD

**Issue by pawlowski** [solid/solidproject.org#410]
On your main page: 

  https://solidproject.org/

there is a section "Solid is great for..." and underneath is a link to "Enterprises" which goes here:

  https://solidproject.org/for-enterprises

and that URL is a 404.

**Comment by Vinnl** [comment]
Thanks for reporting this. It appears that you're getting an older version of the homepage (from a cache somewhere) that points to a page that was removed. Could you try if a hard refresh of the homepage (<kbd>Ctrl</kbd>+<kbd>F5</kbd> on most systems, [see here](https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache) if that doesn't suffice) results in a different page that no longer includes that link?

@justinwb I suppose we could add a redirect from there to elsewhere, or if there's no proper replacement (yet? IIRC you called for the page to be added initially? :) ), we could add some useful message here informing people of what happened and how to clear their cache, assuming that that is the issue?

**Comment by pawlowski** [comment]
Wow this is a totally different frontpage now... yes, I revisited the page and it no longer has those links. I had never visited this site before, so I didn't have a cached copy of the page.

**Comment by Vinnl** [comment]
Thanks for the info @pawlowski.

@justinwb You said there were Netlify credentials, could we use that to host the site in the short term? Would allow us to both avoid the tragically slow builds, the awkward setup with the preview site at a known domain, and hopefully GitHub Pages serving some pages from cache and others not, which it appears is what has happened here.

**Comment by justinwb** [comment]
@Vinnl @pawlowski Given that the links are cleaned up, and we've got netlify into the build process - I believe we can close this out now?

**Comment by Vinnl** [comment]
@justinwb We've got Netlify for the preview deployments, but the main site is still hosted on GitHub Pages, which appears to inconsistently cache things. We could consider hosting the site itself on Netlify as well?

**Comment by justinwb** [comment]
> @justinwb We've got Netlify for the preview deployments, but the main site is still hosted on GitHub Pages, which appears to inconsistently cache things. We could consider hosting the site itself on Netlify as well?

Closing this as we're now deploying production to netlify per suggestion from @Vinnl  ✅
