### ISSUE TITLE
Consider setting up a redirect for /for-developers/apps/

### ISSUE THREAD

**Issue by megoth** [solid/solidproject.org#428]
**Search terms you've used**

/for-developers/apps/

**Is your feature request related to a problem? Please describe.**

The welcome post at forum.solidproject.org (https://forum.solidproject.org/t/welcome-to-the-official-solid-community-forum/8) links to https://solidproject.org/for-developers/apps/, and currently it returns a 404.

**Describe the solution you'd like**

I think a redirect to a relevant page would be good, perhaps https://solidproject.org/developers/ or https://solidproject.org/developers/tutorials/getting-started.

**Comment by justinwb** [comment]
Thanks for raising @megoth! Agree - redirect is the right solution
