### ISSUE TITLE
Visible link to the community forum

### ISSUE THREAD

**Issue by scenaristeur** [solid/solidproject.org#443]
Hi is it normal that the link to the community forum  https://forum.solidproject.org/ has disappear on top of  https://solidproject.org 
I think it should be on top with "developper" & "user" as it was in the past. and not only in the footer
Exploring the forum is a good way to get informed & take confidence & get involved

**Comment by Vinnl** [comment]
Assigned to @justinwb who oversaw the website restructuring.

**Comment by justinwb** [comment]
@scenaristeur Thanks for raising this. Changes are still in progress. As part of those we'll make sure the forum is featured and linked prominently - even if it's not a primary navigation item.

**Comment by justinwb** [comment]
Resolved by @kay-kim in #518
