### ISSUE TITLE
This Month in Solid - This account is temporarily unable to receive new subscribers.

### ISSUE THREAD

**Issue by GllsBe** [solid/solidproject.org#485]
**Search terms you've used**

- Mailing
- Mail
- This month
- Subscribers

**Describe the bug**
When you fill in your e-mail adress in the "This month in Solid" part of the page and complete the Captcha, then you get the following error: "This account is temporarily unable to receive new subscribers."

You'll get an e-mail to confirm your address, but clicking the verify link will bring you to a 500 ERROR.

**To Reproduce**
1. Go to https://solidproject.org/
2. Scroll to the bottom
3. Fill in your e-mail address in "This Month in Solid"
4. Click on subscribe
5. Complete the captcha in the new window
6. See error

**Expected behavior**
I expected to be subscribed to the mailinglist.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/18401063/104191766-39c69600-541e-11eb-9944-f02c0a2359ef.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 84.0.2 (64-bits)

**Comment by Vinnl** [comment]
Hi @GllsBe, thanks for reporting it. We seem to be hitting a quota limit and are working with Mailchimp to raise that. We hope to have that resolved quickly, and I’ll report back here when we do. Apologies for the inconvenience.

**Comment by Vinnl** [comment]
Hi @GllsBe, it should now be working again! Please let us know if you still encounter problems.
