### ISSUE TITLE
As an end-user, can we chose any other web hosting client, other than Amazon? Please

### ISSUE THREAD

**Issue by gatewaytoparadise** [solid/solidproject.org#502]
If you plan on having Amazon host your project, there is a very real contingency that your project will be hindered. Why, you may ask? The whole world saw Amazon engage in Stasi style censorship when they kicked Parler off of their AWS servers.  Since you are striving to develop a decentralized internet, fundamentally based on free-speech, may I please recommend EPIK to host your data (instead of Amazon)?  [](https://www.epik.com) I have no affiliation with them, but as a freedom-loving American and a believer that the internet should be free and uncensored for ALL PEOPLE - a vision I also presume that is shared by your Solid Project Team to bring about a new and revised decentralized internet.  EPIK has proven to be a free speech bastion among a time of prolific censorship.  A decentralized internet ontology is about freedom. If you use Amazon's EC2, or any of their Amazon Web Services, there is a chance they could give your Solid Project the boot too (since past action on Amazon's behalf predicts future behavior).  And knowing this, it would save time and money to not have to rebuild your project over, much like Parler is having to do now.  Just something maybe to consider during your Sprint Planning meeting, or Sprint Review (?), similar to how the military has contingency plans in place for when the unexpected occurs. And if you you need any Automation Engineers, or SDET's, I'd love to help as I truly believe in your mission! :) Wishing you all the best! Sincerely, Nick

**Comment by Vinnl** [comment]
Hi @gatewaytoparadise, this issue tracker pertains the solidproject.org website, so I'll answer for that first. We currently host the website on Netlify, but given that it consists of just static files, it would be trivial to switch it to another host if needed.

If you're talking about Solid itself, it really is up to the user to determine who hosts their Pod. In fact, that's kind of the point :) You can even host it yourself if you prefer.

Given that there's no action for us to undertake with regards to the website, I'll close this ticket for now. Let me know if I misjudged.
