### ISSUE TITLE
Tagline brainstorm

### ISSUE THREAD

**Issue by InruptKelly** [solid/solidproject.org#51]
The tagline at the top of the site — "A standard that makes the web work for you" — is nice and succinct. But I wonder if it may be describing the promise of Solid too narrowly. In my experience, it's good to set people's sights on the big vision and then explain the specifics.

With that in mind, I thought I'd try my hand at suggesting some other possibilities to see if any of them resonate.

"The foundation for the next era of the web"
"Foundational technology for the next era of the web"
"The tech stack for a secure, innovative web"
"The future of secure, innovative apps on the web"
"The web as it was meant to be"
"A web that works for everyone"
"Reshaping the web"
"A new ecosystem of data and applications"
"Reigniting the web's true potential"
"Rebuilding a web for everyone"
"Web technology for a new era of innovation"
"For a new era of innovation"
"The foundation for a new era of online innovation"
"Forging the future of the web"
"The future of the web, today"

I can keep going! But I'll stop here for now.

**Comment by Mitzi-Laszlo** [comment]
Tim has picked this up on https://github.com/solid/solidproject.org/issues/239
