### ISSUE TITLE
getting-started: some text is black on black

### ISSUE THREAD

**Issue by jcollum** [solid/solidproject.org#643]
https://solid.github.io/developers/tutorials/getting-started

![2021-10-22_13-49-02](https://user-images.githubusercontent.com/704514/138521188-5c696e29-8617-4544-bdf5-5468d700d129.png)

Chrome 94

**Comment by Vinnl** [comment]
Hi @jcollum, looks like you were using an outdated link! I've removed that site, the correct link is https://solidproject.org/developers/tutorials/getting-started. Let us know if you see anything else!
