### ISSUE TITLE
Update team affiliations

### ISSUE THREAD

**Issue by kjetilk** [solid/solidproject.org#666]
I'm just about to submit a PR to update my affiliation (so don't worry about that), but I noticed that others need to do that too.

@MarrelleBailey , @jaxoncreed and @Vinnl has changed, as far as I have noticed.

**Comment by jeff-zucker** [comment]
Nice issue number :-).  Please keep in mind that in addition to the solidproject.org listing, the actual RDF source of truth is maintained by Tim at https://solidproject.solidcommunity.net/.

**Comment by jeff-zucker** [comment]
^^ This is not currently relevant to changes in affiliation, only to group membership and WebID.  But eventually we will pull the solidproject.org team data from solidproject's pod.

**Comment by Vinnl** [comment]
Yep, no longer at Inrupt, involved on a personal title now!

**Comment by kjetilk** [comment]
Alright, my WebID doesn't change, that's still NSS running on my personal box in my basement :-) But I understand it doesn't take the text from there?

I sent my PR in #668 , please review and merge as appropriate.
