### ISSUE TITLE
Consider updating newsletter/archive to clarify document status

### ISSUE THREAD

**Issue by csarven** [solid/solidproject.org#810]
From https://matrix.to/#/!SAxwHkjwGMySumDKgq:gitter.im/$A0MYpo0qYeqdsuLgr0ctZib8CcA-wyiu1JoeqCEFT0A :

>Also [..] https://solidproject.org/newsletter/archive should be removed, if there is no newsletter issued anymore. It gives a bad impression, to appear to have no news since 2021.

Perhaps not removed because it still has historical information that's useful, but there can be information at the top of the document indicating the status. There is however an open PR from 2023-05-09 on attempting to update the process on newsletters: https://github.com/solid/process/pull/321 as it was deemed to be still in Solid Team's scope: https://github.com/solid/team/pull/39/files#diff-5c895efd51a3f89afa1c274ad4a65f660a97094e38a027c318664c329b8b1983

Related: https://github.com/solid/solidproject.org/issues/811

**Comment by michielbdejong** [comment]
This is resolved by https://github.com/solid/solidproject.org/pull/891
