### ISSUE TITLE
add experimental Pods to developer listing

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/solidproject.org#84]
# Experimental Solid Servers

The following servers are intended for experimental use and testing of new, unstable instances of a Solid server implementation. There should be no expectation of consistent availability for any server in this list, nor should there be an expectation of reliability or availability of data stored within. Created accounts may be deleted, or corrupted, based on experimental work.

In short, these are made for testing the latest, bleeding edge features and capabilities. Unless that's what you're doing, don't use any of these.

| Link | Responsible for Hosting| Location of Hosting | Solid Server Version |
|-------------------|-------------------|-------------------|-------------------|
|https://solid.pldn.nl/ |[PLDN](http://www.pilod.nl/wiki/Platform_Linked_Data_Nederland)|-------------------|-------------------|
| https://solid.community/| started at [Solid MIT academic project](https://solid.mit.edu) | UK |           NSS 5.x          |
| https://solid.openlinksw.com:8444 |   [OpenLink Software](https://www.openlinksw.com/)  |         USA         |        NSS 4.x       |
| https://solid.openlinksw.com:8445 |   [OpenLink Software](https://www.openlinksw.com/)  |         USA         |        NSS 5.x       |
| https://dev.inrupt.net |  [Inrupt, Inc.](https://www.inrupt.com/)  |         USA         |        NSS 5.x       |
| https://solidweb.org         |                         [Matthias Evering](https://github.com/ewingson)                      |                        Germany                         |         NSS 5.x          |        
|https://ld.solidbase.info|https://github.com/y0va|?|NSS 5.1.0|

https://github.com/solid/solid-idp-list/blob/gh-pages/services.json

**Comment by kjetilk** [comment]
> Currently, https://solidtest.space redirects to a dubious blog?

Yes, I filed multiple PRs on that immediately after we discovered it. We shouldn't link to it as it drives traffic and therefore ad revenue to squatters.

**Comment by Potherca** [comment]
Regarding `solidtest.space`, I came across it at https://databox.me/:

> databox.me is currently not accepting new users
>  Please consider solid.community or solidtest.space instead.

Not sure where I should report that so it can be changed?

**Comment by Mitzi-Laszlo** [comment]
https://github.com/solid/solidproject.org/pull/260 just created a pull to make this issue happen

**Comment by Mitzi-Laszlo** [comment]
@Potherca seems like databox is no longer taking users in any case
