### ISSUE TITLE
Missing URLs to tutorials in redesign

### ISSUE THREAD

**Issue by megoth** [solid/solidproject.org#850]
In the upcoming redesign there are missing URLs for tutorials on the "For developers"-page.

- Java tutorial by Inrupt (https://docs.inrupt.com/developer-tools/java/client-libraries/getting-started/)
- Javascript tutorial by Inrupt (https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/getting-started/)
- Using LDO to build a Solid Application for React by O.team (https://ldo.js.org/guides/solid_react/)
- Creating Vocabularies tutorial (https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/generate-vocabulary-artifacts/)
- How to Build a Solid To-Do App with React tutorial by Virginia Balseiro (https://virginiabalseiro.com/blogposts/tutorial-create-a-solid-to-do-app)
- Ember Solid by Nextcloud (https://nextcloud.hellofuture.be/s/nYYNwGceFSNotJY)

I've added URLs that _I think_ are correct, but need to verify this.

Maybe @oolivo can verify the URLs for Inrupt resources, @jaxoncreed can confirm for O.team, @VirginiaBalseiro can confirm the one on her blog, and @michielbdejong can confirm for Nextcloud?

**Comment by michielbdejong** [comment]
"Ember Solid by Nextcloud" -> "Ember Solid by [Aad Versteden](https://github.com/madnificent)"

**Comment by michielbdejong** [comment]
PR ^
