### ISSUE TITLE
Missing organizations in redesign

### ISSUE THREAD

**Issue by megoth** [solid/solidproject.org#851]
I'm looking over the list of organizations in the new redesign, and currently there's only BBC Research & Development listed there.

Which organizations should we list here?

**Comment by michielbdejong** [comment]
You can just add all orgs you can think of, i would say. I don't think we had a list of orgs on the old website

**Comment by michielbdejong** [comment]
This is still a blocker:
<img width="1616" alt="Screenshot 2024-04-04 at 08 50 06" src="https://github.com/solid/solidproject.org/assets/408412/779757a6-0bfb-4289-9981-412769f56b02">
