### ISSUE TITLE
Events list per year is too wide

### ISSUE THREAD

**Issue by michielbdejong** [solid/solidproject.org#858]
In the `2023-redesign` branch, all events for a given year are in a horizontal list.
This means they run off the screen when there are more than 5 events in one year.

**Comment by csarven** [comment]
Good catch. Please review / have a look at https://github.com/solid/solidproject.org/pull/869 aiming to resolve this. Since no typographical guidelines for various kinds of information was provided, we're bound to run into these random issues all over the website.
