### ISSUE TITLE
Maintain Users section in the new design

### ISSUE THREAD

**Issue by csarven** [solid/solidproject.org#859]
The current design includes the "Users" section. The proposed design removes it. This is a regression in the design considering the Solid's aim is first and foremost to empower users.

Issue for 

>"Users" sections are not in the current design. We're planning to re-introduce the sections in an upcoming separate PR

mentioned in https://github.com/solid/solidproject.org/pull/836#issue-2103520237

**Comment by michielbdejong** [comment]
Thanks for adding this!
<img width="1608" alt="Screenshot 2024-04-09 at 15 10 07" src="https://github.com/solid/solidproject.org/assets/408412/57bfdc55-daed-4e98-9f3e-2d5ab5c16a6f">
