### ISSUE TITLE
/TR folder in redesign?

### ISSUE THREAD

**Issue by michielbdejong** [solid/solidproject.org#874]
Regarding https://solidproject.org/terms and for instance https://solidproject.org/TR/protocol
We should make sure that all those URLs stay accessible, probably?

**Comment by csarven** [comment]
I've already added [Terms](https://github.com/solid/solidproject.org/blob/2023-redesign/terms.html) in the [2023-redesign](https://github.com/solid/solidproject.org/tree/2023-redesign), when we discovered this.

See https://github.com/solid/solidproject.org/blob/main/website-strategy.md#sitemap for actual tracking of website assets.

Resources under `/TR/` is handled by Netlify redirect and served from `solid/specification` repo (GH Pages).

**Comment by michielbdejong** [comment]
Great!
