### ISSUE TITLE
Simplify staging into a single repository

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solidproject.org#92]
As I found out in solid/solid.github.io#242, two repositories are currently being used:
- https://github.com/solid/solid.github.io/ for staging
- https://github.com/solid/solidproject.org/ for production

What's difficult is that both repositories are out of sync. So not everything _can_ be edited in this repository, simply because some things aren't here yet.

Is there a technical reason for this split?

I propose to work in a single repository https://github.com/solid/solidproject.org/, and use different branches there for staging and production, with the default branch being staging. The staging site can then be published somewhere else via CI.

Thoughts?

**Comment by RubenVerborgh** [comment]
- The staging environment has been moved to [the `staging` branch of `solid/solidproject.org`/](https://github.com/solid/solidproject.org/tree/staging).
- [The `master` branch of `solid/solidproject.org`/](https://github.com/solid/solidproject.org/tree/master) is still published at https://solidproject.org/.
- [The `staging` branch of `solid/solidproject.org`/](https://github.com/solid/solidproject.org/tree/staging) is now automatically published at https://solid.github.io/.
- All issues have been ported.
- The process change has been requested at https://github.com/solid/process/pull/181.

**Comment by Vinnl** [comment]
Fantastic, thanks @RubenVerborgh!
